config/routes.rb
EHR::Application.routes.draw do
  devise_for :users

  resources :boxes

  resources :roles

  resources :companies

  resources :jobs do
    get :apply, :on => :member
  end

  resources :events

  resources :users

  resources :notifications

  root :to => 'home#index', :via => [:get]

end

app/models/job.rb
class Job < ActiveRecord::Base
  attr_accessible :id, :job_title, :location
end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController
  # GET /jobs
  # GET /jobs.json
  def index
    @jobs = Job.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @jobs }
    end
  end

  # GET /jobs/1
  # GET /jobs/1.json
  def show
    @job = Job.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @job }
    end
  end

  # GET /jobs/new
  # GET /jobs/new.json
  def new
    @job = Job.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @job }
    end
  end

  # GET /jobs/1/edit
  def edit
    @job = Job.find(params[:id])
  end

  # POST /jobs
  # POST /jobs.json
  def create
    @job = Job.new(params[:job])

    respond_to do |format|
      if @job.save
        format.html { redirect_to @job, notice: 'Job was successfully created.' }
        format.json { render json: @job, status: :created, location: @job }
      else
        format.html { render action: "new" }
        format.json { render json: @job.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /jobs/1
  # PUT /jobs/1.json
  def update
    @job = Job.find(params[:id])

    respond_to do |format|
      if @job.update_attributes(params[:job])
        format.html { redirect_to @job, notice: 'Job was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @job.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /jobs/1
  # DELETE /jobs/1.json
  def destroy
    @job = Job.find(params[:id])
    @job.destroy

    respond_to do |format|
      format.html { redirect_to jobs_url }
      format.json { head :no_content }
    end
  end

  def apply
    UserJobRelation.find_or_create_by_user_id_and_job_id(1, params[:id])

    notification = Notification.new
    notification[:message] = 'Kim apply new job'
    notification[:sender_id] = 1
    notification[:receiver_id] = 1
    notification.save!

    redirect_to request.referer
  end
end

app/helpers/jobs_helper.rb
module JobsHelper
end

app/views/jobs/_form.html.haml
= form_for @job do |f|
  - if @job.errors.any?
    #error_explanation
      %h2= "#{pluralize(@job.errors.count, "error")} prohibited this job from being saved:"
      %ul
        - @job.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :id
    = f.number_field :id
  .field
    = f.label :job_title
    = f.text_field :job_title
  .field
    = f.label :location
    = f.text_field :location
  .actions
    = f.submit 'Save'

app/views/jobs/edit.html.haml
%h1 Editing job

= render 'form'

= link_to 'Show', @job
\|
= link_to 'Back', jobs_path

app/views/jobs/index.html.haml
%h1 Listing jobs

%table
  %tr
    %th Id
    %th Job title
    %th Location
    %th
    %th
    %th
    %th

  - @jobs.each do |job|
    %tr
      %td= job.id
      %td= job.job_title
      %td= job.location
      %td= link_to 'Show', job
      %td= link_to 'Edit', edit_job_path(job)
      %td= link_to 'Destroy', job, :method => :delete, :data => { :confirm => 'Are you sure?' }
      %td= link_to 'Apply', job_path(job) + '/apply'

%br

= link_to 'New Job', new_job_path

app/views/jobs/new.html.haml
%h1 New job

= render 'form'

= link_to 'Back', jobs_path

app/views/jobs/show.html.haml
%p#notice= notice

%p
  %b Id:
  = @job.id
%p
  %b Job title:
  = @job.job_title
%p
  %b Location:
  = @job.location

= link_to 'Edit', edit_job_path(@job)
\|
= link_to 'Back', jobs_path