config/routes.rb
EHR::Application.routes.draw do
  devise_for :users

  resources :boxes

  resources :roles

  resources :companies

  resources :jobs do
    get :apply, :on => :member
  end

  resources :events

  resources :users

  resources :notifications

  root :to => 'home#index', :via => [:get]

end

app/models/notification.rb
class Notification < ActiveRecord::Base
  attr_accessible :id, :message, :receiver_id, :sender_id

  belongs_to :receiver, class_name: "User", foreign_key: "receiver_id"
  belongs_to :sender, class_name: "User", foreign_key: "sender_id"
end

app/controllers/notifications_controller.rb
class NotificationsController < ApplicationController
  # GET /notifications
  # GET /notifications.json
  def index
    @notifications = Notification.includes(:sender, :receiver).all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @notifications }
    end
  end

  # GET /notifications/1
  # GET /notifications/1.json
  def show
    @notification = Notification.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @notification }
    end
  end

  # GET /notifications/new
  # GET /notifications/new.json
  def new
    @notification = Notification.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @notification }
    end
  end

  # GET /notifications/1/edit
  def edit
    @notification = Notification.find(params[:id])
  end

  # POST /notifications
  # POST /notifications.json
  def create
    @notification = Notification.new(params[:notification])

    respond_to do |format|
      if @notification.save
        format.html { redirect_to @notification, notice: 'Notification was successfully created.' }
        format.json { render json: @notification, status: :created, location: @notification }
      else
        format.html { render action: "new" }
        format.json { render json: @notification.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /notifications/1
  # PUT /notifications/1.json
  def update
    @notification = Notification.find(params[:id])

    respond_to do |format|
      if @notification.update_attributes(params[:notification])
        format.html { redirect_to @notification, notice: 'Notification was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @notification.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /notifications/1
  # DELETE /notifications/1.json
  def destroy
    @notification = Notification.find(params[:id])
    @notification.destroy

    respond_to do |format|
      format.html { redirect_to notifications_url }
      format.json { head :no_content }
    end
  end

  #==================================================================
  #interview appointment
  def interview_appointment_approve

  end

  def interview_appointment_reject

  end

  #==================================================================
  #interview
  def interview_approve

  end

  def interview_reject

  end
end

app/helpers/notifications_helper.rb
module NotificationsHelper
end

app/views/notifications/_form.html.haml
= form_for @notification do |f|
  - if @notification.errors.any?
    #error_explanation
      %h2= "#{pluralize(@notification.errors.count, "error")} prohibited this notification from being saved:"
      %ul
        - @notification.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :id
    = f.number_field :id
  .field
    = f.label :message
    = f.text_field :message
  .field
    = f.label :sender_id
    = f.number_field :sender_id
  .field
    = f.label :receiver_id
    = f.number_field :receiver_id
  .actions
    = f.submit 'Save'

app/views/notifications/edit.html.haml
%h1 Editing notification

= render 'form'

= link_to 'Show', @notification
\|
= link_to 'Back', notifications_path

app/views/notifications/index.html.haml
%h1 Listing notifications

%table
  %tr
    %th Id
    %th Message
    %th Sender
    %th Receiver
    %th
    %th
    %th

  - @notifications.each do |notification|
    %tr
      %td= notification.id
      %td= notification.message
      %td= notification.sender.name
      %td= notification.receiver.name
      %td= link_to 'Show', notification
      %td= link_to 'Edit', edit_notification_path(notification)
      %td= link_to 'Destroy', notification, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Notification', new_notification_path

app/views/notifications/new.html.haml
%h1 New notification

= render 'form'

= link_to 'Back', notifications_path

app/views/notifications/show.html.haml
%p#notice= notice

%p
  %b Id:
  = @notification.id
%p
  %b Message:
  = @notification.message
%p
  %b Sender:
  = @notification.sender_id
%p
  %b Receiver:
  = @notification.receiver_id

= link_to 'Edit', edit_notification_path(@notification)
\|
= link_to 'Back', notifications_path