config/routes.rb
EHR::Application.routes.draw do
  devise_for :users

  resources :boxes

  resources :roles

  resources :companies

  resources :jobs do
    get :apply, :on => :member
  end

  resources :events

  resources :users

  resources :notifications

  root :to => 'home#index', :via => [:get]

end

app/models/box.rb
class Box < ActiveRecord::Base
  attr_accessible :authentication_token, :hash, :id, :interviewee, :name
end

app/controllers/boxes_controller.rb
class BoxesController < ApplicationController
  # GET /boxes
  # GET /boxes.json
  def index
    @boxes = Box.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @boxes }
    end
  end

  # GET /boxes/1
  # GET /boxes/1.json
  def show
    @box = Box.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @box }
    end
  end

  # GET /boxes/new
  # GET /boxes/new.json
  def new
    @box = Box.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @box }
    end
  end

  # GET /boxes/1/edit
  def edit
    @box = Box.find(params[:id])
  end

  # POST /boxes
  # POST /boxes.json
  def create
    @box = Box.new(params[:box])

    respond_to do |format|
      if @box.save
        format.html { redirect_to @box, notice: 'Box was successfully created.' }
        format.json { render json: @box, status: :created, location: @box }
      else
        format.html { render action: "new" }
        format.json { render json: @box.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /boxes/1
  # PUT /boxes/1.json
  def update
    @box = Box.find(params[:id])

    respond_to do |format|
      if @box.update_attributes(params[:box])
        format.html { redirect_to @box, notice: 'Box was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @box.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /boxes/1
  # DELETE /boxes/1.json
  def destroy
    @box = Box.find(params[:id])
    @box.destroy

    respond_to do |format|
      format.html { redirect_to boxes_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/boxes_helper.rb
module BoxesHelper
end

app/views/boxes/_form.html.haml
= form_for @box do |f|
  - if @box.errors.any?
    #error_explanation
      %h2= "#{pluralize(@box.errors.count, "error")} prohibited this box from being saved:"
      %ul
        - @box.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :id
    = f.number_field :id
  .field
    = f.label :name
    = f.text_field :name
  .field
    = f.label :hash
    = f.text_field :hash
  .field
    = f.label :authentication_token
    = f.text_field :authentication_token
  .field
    = f.label :interviewee
    = f.number_field :interviewee
  .actions
    = f.submit 'Save'

app/views/boxes/edit.html.haml
%h1 Editing box

= render 'form'

= link_to 'Show', @box
\|
= link_to 'Back', boxes_path

app/views/boxes/index.html.haml
%h1 Listing boxes

%table
  %tr
    %th Id
    %th Name
    %th Hash
    %th Authentication token
    %th Interviewee
    %th
    %th
    %th

  - @boxes.each do |box|
    %tr
      %td= box.id
      %td= box.name
      %td= box.hash
      %td= box.authentication_token
      %td= box.interviewee
      %td= link_to 'Show', box
      %td= link_to 'Edit', edit_box_path(box)
      %td= link_to 'Destroy', box, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Box', new_box_path

app/views/boxes/new.html.haml
%h1 New box

= render 'form'

= link_to 'Back', boxes_path

app/views/boxes/show.html.haml
%p#notice= notice

%p
  %b Id:
  = @box.id
%p
  %b Name:
  = @box.name
%p
  %b Hash:
  = @box.hash
%p
  %b Authentication token:
  = @box.authentication_token
%p
  %b Interviewee:
  = @box.interviewee

= link_to 'Edit', edit_box_path(@box)
\|
= link_to 'Back', boxes_path